sudo: required 

language: bash 

#env:
#  global:
#    - secure: Y4atrq/6OE0mFeABv2OsGvitUKjoqwUX5i73Qfqz9ER8SlnnqzzMfRHmtSZgjL5VhSYV9WGn+L0+6eRfCDcU+zuBQsv43d/+GtcYXBx7VM/As1R8SrFh6j0u83AKi2S3VeN+FkXUuLMJoIFql6wqpmxe8torJB3ABECAc4n3+A9V8aJv5Zh67vTo/uUqZfzWGYK7pU4c2pvIl8uguo0wMYENTi6yedDn6LgooWFBp/kSKq/vU9kna6N2GqxhMUCeylZOuc/BZiHWbBOmrEzPsp+ELFxVQgSEN2slv21LwFk7yAK2WOwXkIh4K/H9++rq++WCyuQBkby4tMAdJT4VrdDfR+hvBB6kNLJqOgczQUWNvCp1Wvy4eYU5ndun9/4w1Wna+QIMXC2T9YW/0e2j0/SrTWXeFsw2pTgwZ33HSdR0+0zfW/gU8QN0vbN5FmkwQK97piHNLZ4U7/9UBr6PyavkzkLagmHUpNGXOgS9QG3I9aN78T5oLdo4DfgQ8Isx8+C5pc7W0M5aim1XQwga4kSee4wf4+c0mMfj4UZH5pG9GRvDBcJLdzf3QHC2gFbsy6Wr98RlTtuSDJs1ioi5v1z2sQ+wHCZi2xbBh8qm1YW0q5XvN6hwu111qnYZoyULK/cERGB2vezQamsPwe3JgcmNVkJ8zKDWQWTEIG9wDW4=
#    - secure: QHI3VtvoXgLcO8+jR/7f+PtU+3DW9zVwnP9YuSHokSW80SYrNKtXrkKJCC5QPK0/uY5it5BMWZvWMxG4Wh/+mHXTjwmweld0kV6V5wqHoOb4lRz5XGTpFZYw4FzGRR9vxxt13eOXW0WDVo6riY0QJxAhWhPxP2tHDuvKNBPWFZTgVbpnGBNCG9IHNb2ShmGhbSr+eBgDc05OQoFALUBdZOuVwoBmkKuDjO3yGKR8Qz2QMeKwEPTTSkfjOMxIEqbtdMI8ZhubT35EZwzze3kFiv+22ZjadIlaKkxZxmyZx9y/qPWIMnjUKIfZ2F74e6JZxodgOr7IKpZJasPmHB6LGCp61RGuuK61SIRuW7aH8IK/zgM56ViOliz6+pcbUuStG81vuwa0zNt8Nd4TSNiOgbZO1V084+P3JDbkfmozzD2vP8aT0FkrUZ7Z3UXsEwqps8RWgLd3c29r5rMi23bq32+wPH6mE/uqkbusPSg5/37Eqinhn/s0N73aeuEBlK0kX6kKkZjmWWLpFgyG5nqpnRVH6cf6Ga/fn62UbWatRt6s+l3MnBbW+9uMqf5YMypwNGzSBlYYFJKJbvUBzdJKdM3YnzQZAuTaluR3gnTDqJRTf0iTIdcEtk7INTzlkQpkg8zvzAqN/n3+X4+WmA8/gTD5ocsEcl7RTPpZhY9boi0=
     - COMMIT=${TRAVIS_COMMIT::8}

services: 
  - docker

install:
  - echo "install nothing!" 

script:
  - docker --version 
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build images
#  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  
  #- export REPO_NAME=$DOCKER_USER/minidlna-armhf
  - export REPO_NAME=sego/minidlna-armhf
  
  - docker build -t $REPO_NAME:$COMMIT
  
  # push
 # - docker tag $REPO_NAME:$COMMIT $REPO_NAME:$TAG
 #  - docker tag $REPO_NAME:$COMMIT $REPO_NAME:travis-$TRAVIS_BUILD_NUMBER
 # - docker push $REPO_NAME
